### ISSUE TITLE
проблемка.....

### ISSUE THREAD

**Issue by overl** [naweak/vk-raidbot#2]
при отправке команд бот не реагирует никак, что делать?
токен верный, в качестве админа выставил свой цифровой id страницы

**Comment by overl** [comment]
Error: Cannot find module 'express'
Require stack:
- /storage/emulated/0/Pictures/vk-raidbot/bot/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/storage/emulated/0/Pictures/vk-raidbot/bot/server.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/storage/emulated/0/Pictures/vk-raidbot/bot/server.js' ] теперь ещё и это за что......
